version: '3.8'
services:
  rflood:
    container_name: rflood
    image: rflood-next:latest
    pull_policy: never
    ports:
      - "3000:3000"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Winnipeg
      - FLOOD_AUTH=false
      - DOWNLOAD_PATH_SSD=/downloading
      - FINAL_DEST_BASE_HDD=/downloads
    volumes:
      - ./testing/config:/config
      - ./testing/downloads:/downloads
      - ./testing/downloading:/downloading